#!/bin/sh

remote="$1"
url="$2"

if [[ $url =~ heroku ]] ; then
  appname=gs-web-client
  hash_name=GIT_REV
  hash=$(git rev-parse HEAD)
  echo Setting $hash_name to $hash
  heroku config:set $hash_name=$hash --app $appname
fi
exit 0
